apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  labels:
    app: grpc 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc 
  template:
    metadata:
      labels:
        app: grpc 
    spec:
      containers:
      - name: grpc-server 
        image: grpc-server
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

